### ISSUE TITLE
Fatal error: Uncaught RedisException: Connection refused in /php-code/classes/RedisCache.php:44

### ISSUE THREAD

**Issue by asschilling40** [KIMB-technologies/Radio-API#64]
On start of the docker the following error comes up:

2024-09-22 12:29:59 [22-Sep-2024 10:29:59] NOTICE: fpm is running, pid 21
2024-09-22 12:29:59 [22-Sep-2024 10:29:59] NOTICE: ready to handle connections
2024-09-22 17:36:24 [22-Sep-2024 15:36:24] NOTICE: fpm is running, pid 18
2024-09-22 17:36:24 [22-Sep-2024 15:36:24] NOTICE: ready to handle connections
2024-09-22 12:29:59 
2024-09-22 12:29:59 Warning: Undefined array key "CONF_DOMAIN" in /php-code/classes/Config.php on line 32
2024-09-22 12:29:59 
2024-09-22 12:29:59 Warning: Undefined array key "CONF_DOMAIN" in /php-code/classes/Config.php on line 32
2024-09-22 12:29:59 
2024-09-22 12:29:59 Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /php-code/classes/Config.php on line 32
2024-09-22 12:29:59 
2024-09-22 12:29:59 Warning: Undefined array key "CONF_CACHE_EXPIRE" in /php-code/classes/Config.php on line 42
2024-09-22 12:29:59 
2024-09-22 12:29:59 Warning: Undefined array key "CONF_SHUFFLE_MUSIC" in /php-code/classes/Config.php on line 49
2024-09-22 12:29:59 
2024-09-22 12:29:59 Fatal error: Uncaught RedisException: Connection refused in /php-code/classes/RedisCache.php:44
2024-09-22 12:29:59 Stack trace:
2024-09-22 12:29:59 #0 /php-code/classes/RedisCache.php(44): Redis->pconnect('127.0.0.1', 6379)
2024-09-22 12:29:59 #1 /php-code/classes/Cache.php(131): RedisCache->__construct('allowed_domains')
2024-09-22 12:29:59 #2 /php-code/classes/Config.php(287): Cache->__construct('allowed_domains')
2024-09-22 12:29:59 #3 /startup.php(24): Config::parseAllowedDomain(true)
2024-09-22 12:29:59 #4 {main}

**Comment by kimbtech** [comment]
Hi,
as there are many messages about missing values for the configuration parameters, I assume the environment variables are not correctly set.

See: https://github.com/KIMB-technologies/Radio-API/blob/master/docker-compose.yml

Also the redis host is configured using environment variables.

Hope this helps.

**Comment by kimbtech** [comment]
Closing this issue, because there is an answer and no reply that there are still problems.
